### ISSUE TITLE
Quickfix live output

### ISSUE THREAD

**Issue by Shatur** [pianocomposer321/yabs.nvim#1]
Hi! Thank you a lot for you plugin!
I have a suggestion. There is [asynctasks.vim](https://github.com/skywind3000/asynctasks.vim) and it allows to display the output directly in quickfix. It's super useful because you allows to navigate errors directly. It would be nice to have the ability to use a quickfix instead of `consolation.nvim` when you build something that can be used for error navigation.

**Comment by pianocomposer321** [comment]
Sounds like a great idea! I'll start thinking about possible implementations, and probably take a peek at how asynctasks.vim does it as well.

Thanks for the suggestion. I will keep you in the loop.

**Comment by pianocomposer321** [comment]
Update on this:
I’ve been working for a while now on improving the configuration experience, as well as refactoring quite a bit to make it easier to add different output types. In addition, I’m including several output types by default, including terminal (which creates a new terminal without any dependencies), buffer (basically the same as just using `termopen`), quickfix (which, duh, sends output to the quickfix list), and, of course, consolation (which sends the output to the default consolation terminal). Btw, consolation is also getting an update, in part to make it play better with yabs, so that it has a terminal wrapper that commands can be sent to by default, instead of having to make a global variable with the wrapper stored inside it (because nobody likes global variables, right?).

I will push these updates as soon as I get a chance to test them a little more and also figure out github’s new authentication method, which seems to be fighting me right now. Anyway, hopefully I’ll get it done tomorrow or later this week. Then you can let me know if it’s what you were looking for or suggest changes. It should be much easier to work with the code after all the refactoring that I did, so more suggestions are definitely welcome!

**Comment by Shatur** [comment]
Thank you, looking forward to it!

**Comment by pianocomposer321** [comment]
@Shatur Changes have been pushed! See `change_configuration` branch of yabs.nvim, and, if you're interested, the `feature` branch of consolation.nvim.

LMK what you think.

Docs are still to come, you can look at lua/yabs/defaults/init.lua for a configuration example. If you have any questions, fell free to ask!
