### ISSUE TITLE
Make some tasks only available when project file is detected

### ISSUE THREAD

**Issue by Dekker1** [pianocomposer321/yabs.nvim#23]
For languages like CPP and Python many tasks do not depend on the language, but on the chosen infrastructure (e.g., CMake vs Make vs Meson and Poetry / Pipenv). Generally each of these file has its own configuration file placed in the project directory. The same is true for a lot of other tools such as formatters, linters, and testers.

For these applications it would be great to make tasks available when their configuration files are found. This ensures they do not have to be defined when not possible, but they can be shared even between different languages.

P.S. This neovim plugin was really missing in my setup, and I'm really enjoying it so far. I hope you don't mind it I create a few issues with features that I would love to have.

**Comment by pianocomposer321** [comment]
Interesting idea...I'm not exactly sure how to go about implementing it, but I'll think about it.

Thanks for the suggestion!

**Comment by pianocomposer321** [comment]
@Dekker1 Sorry I haven't responded sooner...I actually completely forgot about this issue for a while. If I am reading your example config correctly, it looks like you only have the `cmake_build` task set to run for cpp files. If that's what you want, I would suggest moving all of the `cmake_` tasks from the top-level `tasks` table to the `cpp.tasks` table. The reason you're currently getting the error is because the `default_task` option looks for tasks under the table that the key is in, which is the `cpp` language in this case. The tasks aren't defined there though, so that's why there's the error.

Alternatively, if you want the tasks to be available for all filetypes in that project, you can move the `default_task` key from `cpp` to the top-level `tasks` table. If you want this to be the case only for a specific project and not globally, you can use a .yabs file.

LMK if this fixes it. If it doesn't I'd appreciate it if you could open a separate issue, because I'm less likely to forget about it if the issue is open, and I'd rather not reopen this one for a separate issue.

Thanks.

**Comment by Dekker1** [comment]
@pianocomposer321 

The posted issue was merely my first try at using the PR mentioned above. The issue was later resolved in the PR. I don't think there was really any issue here anymore.

**Comment by pianocomposer321** [comment]
@Dekker1 great, thanks!
