### ISSUE TITLE
Add API to run a command using Yabs

### ISSUE THREAD

**Issue by Shatur** [pianocomposer321/yabs.nvim#3]
I am working on [neovim-cmake](https://github.com/Shatur/neovim-cmake) for working with CMake project. I am currently using Asynctaks to run / build the selected target. But I would like to switch from Asynctasks to yabs as a dependency for my plugin to avoid having two similar plugins (right now I using yabs in my configuration).
Could you add an API to run a command using Yabs?

**Comment by pianocomposer321** [comment]
Hello @Shatur.

I am flattered that you are considering yabs as a dependency for neovim-cmake. However, I would suggest that you either hold off for a while or add the dependency in a separate branch, simply because I’m not entirely sure that yabs is stable as yet. For example, how your config broke after https://github.com/pianocomposer321/yabs.nvim/pull/2. I wish I could guarantee that that was the last time anything like that would happen. And seeing as your plugin already has nearly three times as many stars as this one, I think it’s safe to say that the majority of the user base for this plugin will be users of yours. I would hate for your plugin to break simply because I merged in a breaking change without you knowing.

If you have any suggestions for how you would like the configuration to look, I would appreciate hearing them very much. I would like to get this plugin to a stable state as soon as possible.

Thanks again for your interest in this plugin. Having someone to bounce ideas off of (not to mention as a sanity check) is a very valuable thing I’m learning.
