### ISSUE TITLE
Running dependent tasks based on the result of the task

### ISSUE THREAD

**Issue by Badhi** [pianocomposer321/yabs.nvim#38]
For example, some build tools may not output the compile output to the standard output. Instead it might write it to a file. On such scenario we many need to finish the build command first and then check the status of the build and then run another task which reads the error file and redirect it as the output

Is there an easy way to do it under current framework?

**Comment by pianocomposer321** [comment]
Something like this might work:

```lua
require("yabs"):setup {
  languages = {
    cpp = {
      tasks = {
        build = {
          command = "g++ main.cpp -o main",
          output = "quickfix"
        },
        other_task = {
          command = "echo some other command",
          output = "quickfix"
        }
        build_and_other_task = {
          command = function()
            require("yabs"):run_task("build", {
              on_exit = function(Job, exit_code)
                if exit_code == 0 and other_check() then -- other check could involve opening the error file and checking its contents
                  require("yabs"):run_task("other_task")
                end
              end
            })
          end
        }
      }
    }
  }
}
```

Note that this api (i.e. supplying an `on_exit` function to the arguments table in a `run_task` function call) is experimental, and will not work for all outputs. This is because it works by forwarding that function to the plenary job, and therefore it will only work for outputs that use plenary under the hood. So it won't work for the terminal or the consolation outputs, or any custom output that doesn't make use of the extra arguments.
