### ISSUE TITLE
[rewrite] default runners and outputs

### ISSUE THREAD

**Issue by Supreeeme** [pianocomposer321/yabs.nvim#49]
I've been playing with the rewrite and was struggling with the cryptic error `attempt to index a nil value`. After some digging, I came to realize it's because there are no runners or outputs registered by default, and the built in ones have to be registered with `register_runner` and `register-output`. I think it would be a good idea to have the default runners and outputs already registered, but wasn't sure how you wanted to approach this.

**Comment by pianocomposer321** [comment]
Thank you for trying out the rewrite!

I think the general consensus for lua plugins is that they should not set up and defaults without the user calling the "entry-point" function, which is normally `setup`. The main yabs module does not have a setup function, which may be where the confusion is coming from. I haven't added a setup function for the main module because I haven't fully decided what things should be set up by default, and probably won't until soon before I consider the rewrite to be stable.

If you look at the `yabs.defaults` module, there's a setup function in there however. It essentially registers all of the default runners and outputs, and that's what I've been using while developing the plugin. For now you can use that if you like (`require("yabs.defaults").setup()`), but you should be warned that I may remove that function at any time (though it should go without saying that your config could break at any time when testing unstable software 😁).

I may add something to the readme, so I'll leave this issue open for now to remind me to do so.

Thanks again!

**Comment by pianocomposer321** [comment]
Also, I should probably add some `asssert`ions to make the error message more helpful now that I think about it...what's the full message of the error?

**Comment by Supreeeme** [comment]
I didn't realize that yabs.defaults had a setup function, that works for me then lol. The exact error message:
```
E5108: Error executing lua ...supreme/.config/nvim/plugins/yabs.nvim/lua/yabs/core.lua:62: attempt to index a nil value
stack traceback:
        ...supreme/.config/nvim/plugins/yabs.nvim/lua/yabs/core.lua:62: in function 'init_runner'
        ...supreme/.config/nvim/plugins/yabs.nvim/lua/yabs/core.lua:126: in function 'run_command'
        ...e/.config/nvim/plugins/yabs.nvim/lua/yabs/tasks/task.lua:44: in function 'run'
        ...upreme/.config/nvim/plugins/yabs.nvim/lua/yabs/tasks.lua:32: in function 'run_task'
        [string ":lua"]:1: in main chunk
```
